### ISSUE TITLE
Sandbox Careers Widget?

### ISSUE THREAD

**Issue by johnsampson** [traitify/traitify-js-widgets#8]
It appears that https://cdn.traitify.com/js/widgets/careers.js references the host `https://api.traitify.com`.  Is there a version of careers.js that references `api-sandbox`?  Thank you.

**Comment by tomprats** [comment]
You can use `Traitify.setHost("api-sandbox.traitify.com");` when setting up the library. That will point you to the correct environment

**Comment by tomprats** [comment]
Oops, there was a typo in my comment but I corrected it. The readme also has more examples of what can be configured

**Comment by johnsampson** [comment]
Indeed that resolved it.  I had neglected to copy the ENV check locally.  Thank you @tomprats!
